### ISSUE TITLE
Problem in reading training data for Imagent_Validation_Experiement/base(fc)_ImageNet.py

### ISSUE THREAD

**Issue by JavidanAbdullayev** [aassxun/Equiangular-Basis-Vectors#1]
I have this error when I am running the python3 Imagent_Validation_Experiement/base(fc)_ImageNet.py

`FileNotFoundError: [Errno 2] No such file or directory: '/data3ageNet/ILSVRC/Data/CLS-LOC/train/n03417042/n03417042_1022.JPEG'`

I would appreciate it if you could provide any clue that why this error happens and how can I solve it.

**Comment by aassxun** [comment]
> I have this error when I am running the python3 Imagent_Validation_Experiement/base(fc)_ImageNet.py
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/data3ageNet/ILSVRC/Data/CLS-LOC/train/n03417042/n03417042_1022.JPEG'`
> 
> I would appreciate it if you could provide any clue that why this error happens and how can I solve it.

No such file or directory: '/data3ageNet/ILSVRC/Data/CLS-LOC/train/n03417042/n03417042_1022.JPEG'
Please check the dataloader and **verify that the ImageNet-1K dataset exists and the path is correct**. 
If you haven't download the ImageNet-1K dataset, maybe you could follow https://blog.csdn.net/qq_45588019/article/details/125642466 or other related blogs.

**Comment by JavidanAbdullayev** [comment]
Thank you for your response.
I had a problem with the dataloader, more precisely with the dataset path.
Now it works, thanks!
