### ISSUE TITLE
Failed to generate ebvs

### ISSUE THREAD

**Issue by hcw0098** [aassxun/Equiangular-Basis-Vectors#2]
Thanks for you excellent work. I tried to generate ebvs using _/Generate_EBV/Generate_EBV.py_, with dim = 512 and num_cls = 1000 but failed. The loss didn't converge and I tried to lower the lr to 1e-4 or 1e-5 but it didn't work. So does it mean that  we can't generate ebv when dim < num_cls ?

**Comment by aassxun** [comment]
Hello, you can set threshold as 0.05 (The maximum value of the absolute cosine value of the angle between any two basis vectors) and it will work.

**Comment by hcw0098** [comment]
Thanks, that works!
