### ISSUE TITLE
Basis Vectors dimension greater than or equal  the number of categories?

### ISSUE THREAD

**Issue by bqdeng** [aassxun/Equiangular-Basis-Vectors#3]
Thank you for your work.

It seems that the dimensions of the basis vector are **greater than or equal the number of categories** in the experiment. Is it necessary to construct the basis vector as you mentioned?

Can we use the Unit vector of the number of categories directly?

For example, a basis vector similar to a single hot encoding, rather than a basis vector obtained through training.

thanks

**Comment by aassxun** [comment]
> Thank you for your work.
> 
> It seems that the dimensions of the basis vector are **greater than or equal the number of categories** in the experiment. Is it necessary to construct the basis vector as you mentioned?
> 
> Can we use the Unit vector of the number of categories directly?
> 
> For example, a basis vector similar to a single hot encoding, rather than a basis vector obtained through training.
> 
> thanks

Hello, you might have missed some experiments in the paper. For a fair comparison, in Table 1, 3, and 4 of the main paper, the dimension and class num are the same. Meanwhile, in Table 2 of the main paper, when the class num is fixed at 1000, the dimension is set to 100, 200, 300, 400, 500, 1000, 2000 for comparative experiments. You can see the approximate impact of the dimension on the results from this. In Table 1 of the supplementary materials, you can also see the results when the class num is 100,000 and the dimension is 5000. As for the motivation, it will be better to refer to: https://blog.csdn.net/weixin_43955191/article/details/131248042 . I believe it will help you. Finally, when the class num and dimension are the same, using a one-hot vector is not a problem.
(Paper is available at: https://arxiv.org/pdf/2303.11637.pdf

**Comment by bqdeng** [comment]
ok. Thank you for taking the time to answer for me.
