### ISSUE TITLE
About Generate_EBV.py

### ISSUE THREAD

**Issue by peterzh1** [aassxun/Equiangular-Basis-Vectors#4]
Generate_EBV.py： 
Convergence can only occur when num_cls<=dim, and the training process cannot converge when num_cls>dim. Why is that?

**Comment by aassxun** [comment]
> Generate_EBV.py： Convergence can only occur when num_cls<=dim, and the training process cannot converge when num_cls>dim. Why is that?

Hi，thanks for your attention. Maybe you can refer to issue2: https://github.com/aassxun/Equiangular-Basis-Vectors/issues/2
In fact, you have to set the threshold by yourself (The maximum value of the absolute cosine value of the angle between any two basis vectors).

**Comment by peterzh1** [comment]
> > Generate_EBV.py： Convergence can only occur when num_cls<=dim, and the training process cannot converge when num_cls>dim. Why is that?
> 
> Hi，thanks for your attention. Maybe you can refer to issue2: #2 In fact, you have to set the threshold by yourself (The maximum value of the absolute cosine value of the angle between any two basis vectors).

I set num_cls = 1041 and dim = 384. During traing, mx > 0.9997. Perhaps this problem cannot be solved by adjusting the threshold.

**Comment by aassxun** [comment]
> 

Set num_cls = 1041, dim = 384, threshold = 0.051, lr = 1e-4, step = 10000 and it will work. 
You can refer to https://blog.csdn.net/weixin_43955191/article/details/131248042 for a better understanding of the motivation  and this may help to understand Generate_EBV.py can work and why as long as there is sufficient space, setting a well-defined threshold can ensure that Generate_EBV will hold true..

**Comment by peterzh1** [comment]
Thank you, it works.
